### ISSUE TITLE
For discussion: Refactor users/authorities on backend

### ISSUE THREAD

**Issue by rkaufman13** [codefordc/us-congress-pizza-flag-tracker#104]
Currently user "authorities" (what permissions they have) are declared as properties on the user object, and they're set as strings, such as:
`can_create_update_delete_orders":"Y"`

I just tweaked the way the profile page displays on the frontend. It occurred to me that we may want to store alongside the snake-cased property name, the human-readable name. In JSON it might look like this:
```can_create_update_delete_orders: {name: "Can create, update, or delete orders",auth:false}```

IF the only place where we need the "friendly" names is the profile page, then ignore this, but I suspect it might be helpful to have the friendly names for error messages and the like. 
I realize this might involve a db restructure (separate table for authorities/their descriptions?) and some backend work, so I'm throwing it out for discussion!

**Comment by ethanstrominger** [comment]
@rkaufman13 I changed the names of the fields so marking this as closed
