### ISSUE TITLE
Bug: Previous log id may be calculated incorrectly

### ISSUE THREAD

**Issue by ethanstrominger** [codefordc/us-congress-pizza-flag-tracker#139]
Logic works if status updates move sequentially (no reverts and no skips) and status ids are sequential.  If a status is skipped, status ids are not sequential, or there are revert statuses, the log count will differ from the max status id and so it will either not find a previous log or will find the wrong one.

**Comment by Tmstone** [comment]
The issue was addressed and merged at the last meeting on 4/13/22.
