### ISSUE TITLE
REFACTOR: order logs

### ISSUE THREAD

**Issue by ethanstrominger** [codefordc/us-congress-pizza-flag-tracker#140]
Naming:
get_order_log_uuid => get_most_recent_order_log_uuid (or last, previous)
current_order_log_uuid => most_recent_order_log_uuid (or last, previous)

Unused:
get_max_order_count
sort_order_log_by_order_number

Code can be combined into one line:
       prior_order_log_uuid = LogActions.get_order_log_uuid(order_number)
        previous_order_log_uuid = prior_order_log_uuid

**Comment by Tmstone** [comment]
current_order_log_uuid => most_recent_order_log_uuid (or last, previous) 
The order_log_uuid that is retrieved is the current order_log_uuid or active order_log_uuid. it becomes previous when the new is created.

**Comment by Tmstone** [comment]
The issue was merged at last. meeting April 13, 2022
