### ISSUE TITLE
(Ananda) Backend: Add query by status, state, and office

### ISSUE THREAD

**Issue by Tmstone** [codefordc/us-congress-pizza-flag-tracker#143]
- [ ] backend that responds to the request that includes the 4 or 5 specific search terms with the endpoint `/api/orders?...` https://github.com/codefordc/us-congress-pizza-flag-tracker-frontend/issues/83

https://github.com/codefordc/us-congress-pizza-flag-tracker/blob/main/src/order/order_controller.py#L150-L172

**Comment by thadk** [comment]
https://github.com/codefordc/us-congress-pizza-flag-tracker-frontend/issues/83
