### ISSUE TITLE
ORDER: Default usa state to blank

### ISSUE THREAD

**Issue by ethanstrominger** [codefordc/us-congress-pizza-flag-tracker#27]
It is confusing to have a default value, especially when it doesn't work - better if it defaults to blank.  This may be taken care of by the combo box bug which should be done first.  See issue #17

**Comment by rkaufman13** [comment]
See @mertbagt's open PR on the front-end for an elegant way to handle this

**Comment by mertbagt** [comment]
in AddOrder.js added a blank <option> on the usa_state and office_code select dropdowns on my frontend pull request.  Subject to testing/review we can do the same for the dropdowns at OrdersList.js

**Comment by mertbagt** [comment]
related issue where, if you:
1) put in an order number
2) select a US State
3) select a Cong. Office
4) go back and select a different US State

the submit button has all the values it needs to be enabled, but AddOrder state has an illogical combination of usa_state and office_code values.

(using AddOrder.js to try solutions before touching OrdersList.js) 

added:

  const handleUSSTATEChange = (event) => {
    const { name, value } = event.target;
    setOrder({ ...order, [name]: value, office_code: "" }); 
  };

to reset office_code whenever usa_state updates onChange

and some temporary <h4> component visualizers to see all the values as they change

**Comment by mertbagt** [comment]
@mertbagt
