### ISSUE TITLE
BACKEND ONLY REFACTOR: Backend only: @app.route to routes.py

### ISSUE THREAD

**Issue by ethanstrominger** [codefordc/us-congress-pizza-flag-tracker#29]

**Comment by rajindermavi** [comment]
I agree with this refactor. I think we had a couple of these implemented at some point before removing them.

**Comment by ethanstrominger** [comment]
@Tmstone It did not cause an error.  I agree with tmstone, I will move app.route code to routes.py if @thadk agrees.  We can discuss at meeting.  routes.py seems to be recommended based on brief googling.
