### ISSUE TITLE
NEEDS DISCUSSION: BACKEND: Add created and updated dates as well as created by and updated by for every table

### ISSUE THREAD

**Issue by ethanstrominger** [codefordc/us-congress-pizza-flag-tracker#38]
What are the names of the fields?  What is the best way to do this?  Are all fields needed?

**Comment by rajindermavi** [comment]
This issue was fixed by changes in a previous [commit](https://github.com/codefordc/us-congress-pizza-flag-tracker/commit/e0f0e94e29843da2aa386d318b288f96d1c34f19)
