### ISSUE TITLE
FRONTEND ONLY: unprivledged user redirects

### ISSUE THREAD

**Issue by mertbagt** [codefordc/us-congress-pizza-flag-tracker#47]
If a user doesn't have privileges for a given functionality (add, create, etc), they should be redirected to the login or main view.

**Comment by rkaufman13** [comment]
I believe this is addressed in [17](https://github.com/codefordc/us-congress-pizza-flag-tracker-frontend/pull/17)

**Comment by ethanstrominger** [comment]
Dupe
