### ISSUE TITLE
Populate seed data when run flask db upgrade and modify instructions/scripts for refreshing db

### ISSUE THREAD

**Issue by ethanstrominger** [codefordc/us-congress-pizza-flag-tracker#96]
Current instructions for recreating flag.db:
- del flag.db,
- remove migrations dir,
- run flask db init,
- flask db migrate,
- flask db upgrade,

Issue:
There is not an upgrade path for existing databases.   This is a problem for heroku and causes extra work for developers.

Findings:
- To recreate flag.db you only need to del flag.db and run flask db upgrade. 
- flask db init only needs to be run to create the initial migrations directory 
- Running flask db migrate before flask db upgrade gives you an error if flask.db does not already exist.

Partial fix:

- Change ./restart.sh to delete flag.db and run flask db upgrade
- Update readme.md about when to run the flask db commands.
- Create a new script ./upgrade.sh which only runs the flask db upgrade command

New Issue:
- Running upgrade only does not populate the users, orders, and offices tables.  flask db init would do this, but this should only be run once.

**Comment by thadk** [comment]
I think we need to `git rm -r migrations` rather than `rm -rf migrations`

**Comment by ethanstrominger** [comment]
@thadk We don't need to rm migrations at all.  I am writing up a Slack message.
